name: Shell Commends

# on["push"]
on:
    - push

#    jobs {
#      "run-shell-command" : {
#        "runs-on" : "ubuntu-latest",
#        "steps" : [
#          {
#            "name" : "echo a string",
#            "run" : "echo 'Hello World! this is workflow test'",
#          },
#          {
#            "name": "multiline script",
#            "run": "node --version \n npm --version",
#          },
#        ]
#      }
#    }

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World! this is workflow test"

      - name: multiline script
        run: |
          node --version
          npm --version



